name: Update Completed Issues Counter

on:
  push:
    paths:
      - 'deliverables/arbeitsplan/arbeitsplan.md'
      - '.github/workflows/update-counter.yml'

jobs:
  update_counter:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Git
    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    # Extract and count completed issues
    - name: Count completed issues and update counter
      run: |
        # Define the file path
        FILE="deliverables/arbeitsplan/arbeitsplan.md"

        # Check if the file exists and print contents for debugging
        echo "Checking file at: $FILE"
        cat "$FILE"

        # Count the number of "✅" symbols
        COUNT=$(grep -o "✅" "$FILE" | wc -l)
        echo "Found $COUNT completed issues"

        # Update the "Completed Issues" section
        sed -i "s/^## Overall Completed Issues: .*/## Overall Completed Issues: $COUNT ✅/" "$FILE"

        # Debug: Print updated file contents
        echo "Updated file contents:"
        cat "$FILE"

    # Commit the changes if any
    - name: Commit the changes
      run: |
        git add deliverables/arbeitsplan/arbeitsplan.md
        git commit -m "Update completed issues counter in arbeitsplan.md"

        # Push the changes back to the repository using GITHUB_TOKEN
        git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/domi-cmd/PSE_Abilium.git
