name: Update Issue Counter

on:
  push:
    branches:
      - main
permissions:
  contents: write 

jobs:
  count_done_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Debug Directory Structure
        run: ls -R  

      - name: Count Completed Issues
        run: |
          FILE="deliverables/arbeitsplan/arbeitsplan.md"
          COUNT=$(grep -o "✅" "$FILE" | wc -l)
          sed -i "s/^## Completed Issues: .*/## Completed Issues: $COUNT ✅/" "$FILE"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add "deliverables/arbeitsplan/arbeitsplan.md"
          git diff --quiet && echo "No changes to commit" || (git commit -m "Updated completed issue count" && git push)
