name: Update Issue Counter # Name

on:
  push:
    paths:
      - 'deliverables/arbeitsplan/arbeitsplan.md'
      - '.github/workflows/update-issue-counter.yml'

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Count Completed Issues
        run: |
          FILE="deliverables/arbeitsplan/arbeitsplan.md"
          
          # Debug: Check if the file exists and print its contents
          echo "Checking file at: $FILE"
          cat "$FILE"  # Output the file contents to make sure we can see it

          # Count the number of ✅ symbols
          COUNT=$(grep -o "✅" "$FILE" | wc -l)
          echo "Found $COUNT completed issues"  # Show the counted value

          # Update the counter line (adjusted for "Overall Completed Issues")
          sed -i "s/^## Overall Completed Issues: .*/## Overall Completed Issues: $COUNT ✅/" "$FILE"

          # Debug: Print the file again to ensure the change is made
          echo "Updated file contents:"
          cat "$FILE"

      - name: Commit the changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add deliverables/arbeitsplan/arbeitsplan.md
          git commit -m "Update completed issues counter in arbeitsplan.md"
          
          # Use the GitHub token for authentication
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/domi-cmd/PSE_Abilium.git
